# See LICENSE file for copyright and license details
# libgrapheme - grapheme cluster utility library
.POSIX:

include config.mk

LIB = src/boundary src/codepoint src/grapheme
TEST = test/test
DATA = data/gbp data/emo data/gbt

MAN3 = man/grapheme_bytelen.3
MAN7 = man/libgrapheme.7

all: libgrapheme.a libgrapheme.so $(TEST)

src/boundary.o: src/boundary.c config.mk data/emo.h data/gbp.h grapheme.h
src/codepoint.o: src/codepoint.c config.mk grapheme.h
src/grapheme.o: src/grapheme.c config.mk grapheme.h
test/test.o: test/test.c config.mk data/gbt.h grapheme.h

test/test: test/test.o $(LIB:=.o)

test: $(TEST)
	for m in $(TEST); do ./$$m; done

$(TEST):
	$(CC) -o $@ $(LDFLAGS) $< $(LIB:=.o)

.c.o:
	$(CC) -c -o $@ $(CPPFLAGS) $(CFLAGS) $<

libgrapheme.a: $(LIB:=.o)
	$(AR) rc $@ $?
	$(RANLIB) $@

libgrapheme.so: $(LIB:=.o)
	$(CC) -o $@ -shared $?

data/gbp.h: data/gbp.awk data/gbp.txt
	printf "/* Automatically generated by gbp.awk */\n" > $@
	printf "#include <stdint.h>\n\n" >> $@
	awk -f data/gbp.awk data/gbp.txt >> $@
	printf "\n" >> $@

data/emo.h: data/emo.awk data/emo.txt
	printf "/* Automatically generated by emo.awk */\n" > $@
	printf "#include <stdint.h>\n\n" >> $@
	awk -f data/emo.awk data/emo.txt >> $@
	printf "\n" >> $@

data/gbt.h: data/gbt.awk data/gbt.txt
	printf "/* Automatically generated by gbt.awk */\n" > $@
	printf "#include <stddef.h>\n" >> $@
	printf "#include <stdint.h>\n\n" >> $@
	printf "#include \"../grapheme.h\"\n\n" >> $@
	awk -f data/gbt.awk data/gbt.txt >> $@
	printf "\n" >> $@

data/gbp.txt:
	wget -O $@ https://www.unicode.org/Public/13.0.0/ucd/auxiliary/GraphemeBreakProperty.txt

data/emo.txt:
	wget -O $@ https://www.unicode.org/Public/13.0.0/ucd/emoji/emoji-data.txt

data/gbt.txt:
	wget -O $@ https://www.unicode.org/Public/13.0.0/ucd/auxiliary/GraphemeBreakTest.txt

install: all
	mkdir -p "$(DESTDIR)$(LIBPREFIX)"
	mkdir -p "$(DESTDIR)$(INCPREFIX)"
	mkdir -p "$(DESTDIR)$(MANPREFIX)/man3"
	mkdir -p "$(DESTDIR)$(MANPREFIX)/man7"
	cp -f $(MAN3) "$(DESTDIR)$(MANPREFIX)/man3"
	cp -f $(MAN7) "$(DESTDIR)$(MANPREFIX)/man7"
	cp -f libgrapheme.a "$(DESTDIR)$(LIBPREFIX)"
	cp -f libgrapheme.so "$(DESTDIR)$(LIBPREFIX)"
	cp -f grapheme.h "$(DESTDIR)$(INCPREFIX)"

uninstall:
	for m in $(MAN3); do rm -f "$(DESTDIR)$(MANPREFIX)/man3/`basename $$m`"; done
	for m in $(MAN7); do rm -f "$(DESTDIR)$(MANPREFIX)/man7/`basename $$m`"; done
	rm -f "$(DESTDIR)$(LIBPREFIX)/libgrapheme.a"
	rm -f "$(DESTDIR)$(LIBPREFIX)/libgrapheme.so"
	rm -f "$(DESTDIR)$(INCPREFIX)/grapheme.h"

clean:
	rm -f $(DATA:=.h) $(LIB:=.o) $(TEST:=.o) $(TEST) libgrapheme.a libgrapheme.so

clean-data:
	rm -f $(DATA:=.txt)
